// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package database

import (
	"time"
)

type Book struct {
	ID               int32
	Title            string
	Isbn             string
	Author           string
	Category         string
	Publisher        string
	YearOfPublishing int32
	Img              string
	NumberOfPages    int32
	PersonalRating   float64
	PersonalNotes    string
	ReadStatus       bool
	ReadDate         time.Time
	UserID           int32
}

type Session struct {
	Token  string
	Data   []byte
	Expiry time.Time
}

type User struct {
	ID             int32
	Username       string
	Email          string
	HashedPassword string
	CreatedAt      time.Time
	ListOfBooks    []string
}
